// Mocks generated by Mockito 5.0.15 from annotations
// in moviedb/test/view_model/detail_movie/detail_movie_view_model_test.dart.
// Do not manually edit this file.

import 'dart:async' as _i5;

import 'package:mockito/mockito.dart' as _i1;
import 'package:moviedb/core/models/actor.dart' as _i7;
import 'package:moviedb/core/models/movie.dart' as _i6;
import 'package:moviedb/core/models/movie_detail.dart' as _i2;
import 'package:moviedb/core/models/video_response.dart' as _i3;
import 'package:moviedb/core/services/movie_service.dart' as _i4;

// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis

class _FakeMovieDetail_0 extends _i1.Fake implements _i2.MovieDetail {}

class _FakeVideoResponse_1 extends _i1.Fake implements _i3.VideoResponse {}

/// A class which mocks [MovieService].
///
/// See the documentation for Mockito's code generation for more information.
class MockMovieService extends _i1.Mock implements _i4.MovieService {
  MockMovieService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.Future<List<_i6.Movie>> getPopularMovie(int? page) =>
      (super.noSuchMethod(Invocation.method(#getPopularMovie, [page]),
              returnValue: Future<List<_i6.Movie>>.value(<_i6.Movie>[]))
          as _i5.Future<List<_i6.Movie>>);
  @override
  _i5.Future<List<_i6.Movie>> getUpcoming(int? page, int? pageSize) =>
      (super.noSuchMethod(Invocation.method(#getUpcoming, [page, pageSize]),
              returnValue: Future<List<_i6.Movie>>.value(<_i6.Movie>[]))
          as _i5.Future<List<_i6.Movie>>);
  @override
  _i5.Future<_i2.MovieDetail> getMovieById(int? id) =>
      (super.noSuchMethod(Invocation.method(#getMovieById, [id]),
              returnValue: Future<_i2.MovieDetail>.value(_FakeMovieDetail_0()))
          as _i5.Future<_i2.MovieDetail>);
  @override
  _i5.Future<_i3.VideoResponse> getVideoById(int? id) => (super.noSuchMethod(
          Invocation.method(#getVideoById, [id]),
          returnValue: Future<_i3.VideoResponse>.value(_FakeVideoResponse_1()))
      as _i5.Future<_i3.VideoResponse>);
  @override
  _i5.Future<List<_i7.Actor>> getCastById(int? id) =>
      (super.noSuchMethod(Invocation.method(#getCastById, [id]),
              returnValue: Future<List<_i7.Actor>>.value(<_i7.Actor>[]))
          as _i5.Future<List<_i7.Actor>>);
  @override
  String toString() => super.toString();
}
